### ISSUE TITLE
Files not included

### ISSUE THREAD

**Issue by felixlandicho** [webpixels/boomerang-ui-kit#1]
Hi, i just downloaded the package and notice that on the "SCSS" folder, there's only demo.scss and theme.scss.

Is that normal? Thanks

**Comment by webpixels** [comment]
Hi @felixlandicho, thx for the heads up. And no, that was not normal. I just omitted to add them. Now everything should be in order. Download it again and let me know what you think :smile:

**Comment by felixlandicho** [comment]
Alright, I downloaded it again and everything is there.
Thanks
